ui/src/components/NoResult.tsx, ui/src/modules/app_list/index.tsx, ui/src/modules/version_list/index.module.css, ui/src/modules/version_list/index.tsx, ui/src/routes.tsx
- init brand new version list page
=> feat(ui): version list

.gitignore, api/api_schemas.py, api/application.py, app.py, auth.py
In this implemention, a default auth plugin, BaseAuthPlugin was implemented. This plugin will identify each user as "anonymous". One can change this behavior by developing a class to inherit it.
=> feat: add auth mechanism

ui/src/modules/app_builder/Block/index.tsx, ui/src/modules/app_builder/Block/useValidConnection.ts, ui/src/modules/app_builder/Canvas/index.tsx, ui/src/modules/app_builder/Edge/index.tsx, ui/src/modules/app_builder/index.tsx, ui/src/modules/app_builder/useMutateVersion.ts
=> tweak: boolean edge ux

ui/src/modules/app_builder/index.tsx, ui/src/modules/app_builder/linguflow.type.ts, ui/src/modules/app_builder/useMutateVersion.ts
- fix file button by `keepMounted` prop in Menu:`<Menu shadow="md" width={140} position="bottom-start" opened={opened} onChange={setOpened} keepMounted>`
=> fix(ui): import app

auth.py, patterns/llm.py, requirements.txt
=> observability: support llm usage & cost info

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/config.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml, .github/ISSUE_TEMPLATE/general_issue.yaml, .github/PULL_REQUEST_TEMPLATE.md
Add issue templates for bug reporting, feature request and general issues
=> add issue template

ui/src/modules/app_builder/Canvas/index.tsx, ui/src/modules/app_builder/Canvas/useCopyBlock.ts, ui/src/modules/app_builder/Canvas/useHotKeyMenu.ts
=> feat(ui): support copy & paste

ui/package.json, ui/src/modules/version_list/ConnectionGuidance.tsx, ui/src/modules/version_list/guidance.mdx, ui/vite.config.ts, ui/yarn.lock
=> tweak(ui): guidance

ui/src/modules/app_builder/index.tsx
=> fix(ui): ver id

README.md, auth.py, docker-compose.yaml, ui/Dockerfile, ui/nginx.conf
- Add deploy document for dev & self-hosting
- add self-hosting docker-compose.yaml
=> Add deploy document

ui/src/modules/app_builder/Toolbar/Debug/index.tsx, ui/src/modules/app_list/index.tsx, ui/src/modules/version_list/Header.tsx, ui/src/modules/version_list/index.tsx
=> tweak(ui): show app id in version list header

blocks/__init__.py, blocks/llm.py
Add a new block `Chat_LLM` to support chatting.
=> add chatllm block and add missing blocks in the init file of blocks

examples/ChatGPT3p5-Wrapper.v2024-03-27.1711518920.linguflow.yaml, examples/TiDB Bot demo.v2024-03-27.1711519176.linguflow.yaml
Add two application examples (.yaml) so that users can generate a new application as a template.
=> add 2 application examples(.yaml)

docker-compose.yaml
Modify docker-compose.yaml to use pre-build docker images.
=> deploy: use pre-build docker image for production

docs/deployment/self_host.md
=> Update production deployment method

requirements.txt
Fix the [bug](https://github.com/langfuse/langfuse/issues/1581) from langfuse.
=> upgrade langfuse to fix an bug

ui/src/modules/app_builder/Block/Secret.tsx, ui/src/modules/app_builder/Block/useValidConnection.ts, ui/src/modules/app_builder/index.tsx, ui/src/modules/app_builder/useMutateVersion.ts
Remove the secret when exporting to avoid leaking the secret key.
=> tweak(ui): sanitize secret when export yaml

ui/src/modules/app_builder/Block/DebugInfo.tsx
- Support the no-string output of debug info.
=> fix(ui): debug info

ui/src/modules/app_builder/index.tsx
- form states will be mutated after export yaml.
=> fix(ui): mutate form states after export

patterns/embedding/pinecone.py, requirements.txt
The Pinecone freetier is out of date. And the client must be updated too.
=> update pinecone client

blocks/invoke.py
=> Fix InvokeWithList & InvokeWithDict
